### ISSUE TITLE
Check existence of files in subsample_table

### ISSUE THREAD

**Issue by jma1991** [pepkit/eido#26]
How can I write a schema which will validate the existence of files specified in the subsample table? I almost always specify read1 and read2 in the subsample table because I rarely have just a single pair of FASTQ files per sample (i.e. usually from multiple lanes). The schema below (adapted from the examples page) passes validation without any FASTQ files present so I assume when the read1 and read2 attributes are arrays it doesn't check for the existence of each item in the array?

```
description: Schema
imports:
  - http://schema.databio.org/pep/2.0.0.yaml
properties:
  samples:
    type: array
    items:
      type: object
      properties:
        sample_name: 
          type: string
          description: "Name of the sample"
        read1:
          anyOf:
            - type: string
              description: "Fastq file for read 1"
            - type: array
              items:
                type: string
        read2:
          anyOf:
            - type: string
              description: "Fastq file for read 2 (for paired-end experiments)"
            - type: array
              items:
                type: string
      required_files:
        - read1
        - read2
      files:
        - read1
        - read2
      required:
        - sample_name
        - read1
        - read2
required:
  - samples
```

**Comment by nsheff** [comment]
That's a good point. I am not sure we considered the case of the required files being in subsamples. 

One tricky thing is, should it require them *all* or just *any* specified files to exist in that case?

@stolarczyk have you thought through this?

**Comment by stolarczyk** [comment]
Hey, thanks for reaching out!

> How can I write a schema which will validate the existence of files specified in the subsample table?

It doesn't matter where the sample attributes come from from the eido perspective. Eido processes a `peppy.Project` object that has been altered by the modifiers and with attributes subsample table added.

> passes validation without any FASTQ files present 

I think I got the expected result with the set of files listed below. Is that similar to your setup?

```yaml
pep_version: 2.0.0
sample_table: sample_table.csv
subsample_table: subsample_table.csv
```
sample_table.csv 
```csv
sample_name,attr1,attr2
sample1,val1,val2
sample2,val1,val2
```
subsample_table.csv (the `read1` and `read2` attributes are missing for one of `sample2`)
```
sample_name,read1,read2
sample1,read_file1,read_file2
```
schema.yml  (just copied yours)
```yaml
description: Schema
imports:
  - http://schema.databio.org/pep/2.0.0.yaml
properties:
  samples:
    type: array
    items:
      type: object
      properties:
        sample_name: 
          type: string
          description: "Name of the sample"
        read1:
          anyOf:
            - type: string
              description: "Fastq file for read 1"
            - type: array
              items:
                type: string
        read2:
          anyOf:
            - type: string
              description: "Fastq file for read 2 (for paired-end experiments)"
            - type: array
              items:
                type: string
      required_files:
        - read1
        - read2
      files:
        - read1
        - read2
      required:
        - sample_name
        - read1
        - read2
required:
  - samples
```
