### ISSUE TITLE
Change config key to project

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/eido#71]
In an effort to unify input schemas for eido with output schemas for pipestat, we would like to make the following changes to the input schemas:

1. change `config` key to `project` key.
2. add `type:object` to the beginning of the schema

Example section of the minimal pep example with the modified changes:

```
description: "Schema for a minimal PEP"
version: "2.1.0"
type: object
properties:
  project:
    type: object
    properties:
      name: 
        type: string
        pattern: "^\\S*$"
        description: "Project name with no whitespace"
      pep_version:
        description: "Version of the PEP Schema this PEP follows"
        type: string
      sample_table:
        type: string
        description: "Path to the sample annotation table"

```
